import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { Work_Sans, Poppins } from "next/font/google";
import { Toaster } from "sonner";
import WhatsAppButton from "../components/WhatsAppButton"; 


const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-work-sans",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${workSans.variable} font-[var(--font-poppins)] antialiased`}
      >
        {/* Toast system available globally */}
        <Toaster position="top-center" richColors />

        {/* Global Layout */}
        <Header />
        <main>{children}</main>
        <WhatsAppButton />
        <Footer />
      </body>
    </html>
  );
}
